spring.application.name=gerenciador-carteiras-api
spring.datasource.url=jdbc:mysql://localhost:3306/gerenciador_de_carteiras
spring.datasource.username=root
spring.datasource.password=tecsis
spring.jpa.hibernate.ddl-auto=update



spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

api.security.token.secret=my-secret-key